# ASP.NET Core

trigger:
- main
- development
- feature/*

variables:
  vmImageName: 'ubuntu-latest'

  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/development')]

stages:
- stage: Build

  jobs:
  - job: Build

    pool:
      vmImage: $(vmImageName)

    variables:
      buildConfiguration: 'Release'
      - name: one
          value: initialValue 
      

    steps:
    - script: |
          echo ${{ variables.one }} # outputs initialValue
          echo $(one)
        displayName: First variable pass
      - bash: echo "##vso[task.setvariable variable=one]secondValue"
        displayName: Set new variable value
      - script: |
          echo ${{ variables.one }} # outputs initialValue
          echo $(one) # outputs secondValue
        displayName: Second variable pass
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)' 

    - task: DotNetCoreCLI@2
      displayName: Test    
      inputs:
        command: test
        projects: '$(System.DefaultWorkingDirectory)/UnitTests/SampleTestProject/SampleTestProject.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/development'))
      displayName: Prepare Publish    
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishPipelineArtifact@1
      condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/development'))
      displayName: Publish    
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'drop'


- stage: Deploy
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/development'))

  jobs:
  - deployment: mainDeploy
    condition: and(succeeded(), eq(variables.isMain, true))
    variables:
      - group: CSharp-Prod
    environment: myproduction

    pool:
      vmImage: $(vmImageName)

    strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                echo $(AppName)
                echo $(serviceConnection)
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
                targetPath: '$(Pipeline.Workspace)'
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: $(serviceConnection)
                appType: 'webAppLinux'
                WebAppName: $(AppName)
                packageForLinux: '$(Pipeline.Workspace)/drop/src.zip'

  - deployment: devDeploy
    condition: and(succeeded(), eq(variables.isDev, true))
    variables:
      - group: CSharp-Dev
    environment: mydevelopment

    pool:
      vmImage: $(vmImageName)

    strategy:
        runOnce:
          deploy:
            steps:
            - script:
                echo $(AppName)
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
                targetPath: '$(Pipeline.Workspace)'
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: $(serviceConnection)
                appType: 'webAppLinux'
                WebAppName: $(AppName)
                packageForLinux: '$(Pipeline.Workspace)/drop/src.zip'